export enum Clan {
  VENTRUE = 'VENTRUE',
  MALKAVIAN = 'MALKAVIAN',
  GANGREL = 'GANGREL',
  BRUJAH = 'BRUJAH',
  TOREADOR = 'TOREADOR',
  TREMERE = 'TREMERE',
  NOSFERATU = 'NOSFERATU',
  CAITIFF = 'CAITIFF',
  ASSAMITE = 'ASSAMITE',
  GIOVANNI = 'GIOVANNI',
  TZIMISCE = 'TZIMISCE',
  RAVNOS = 'RAVNOS',
  LASOMBRA = 'LASOMBRA',
  SETHITE = 'SETHITE'
}
