export enum Specialty {
  FINANCE = 'FINANCE',
  LOI = 'LOI',
  MEDIA = 'MEDIA',
  SANTE = 'SANTE',
  POLICE = 'POLICE',
  OCCULTE = 'OCCULTE',
  CRIME = 'CRIME',
  RUE = 'RUE',
  EDUCATION = 'EDUCATION',
  TRANSPORT = 'TRANSPORT',
  INDUSTRIE = 'INDUSTRIE',
  HAUTE_SOCIETE = 'HAUTE_SOCIETE',
  BUREAUCRATIE = 'BUREAUCRATIE',
  RELIGION = 'RELIGION',
  POLITIQUE = 'POLITIQUE'
}
